### ISSUE TITLE
FromAlias 参数报错

### ISSUE THREAD

**Issue by ahan** [MT-Libraries/node-aliyun-dms#2]
你好，我正常使用这个组件是没有问题

然后我看到官网 API文档里有个 FromAlias 参数

> FromAlias String  可选  发信人昵称,长度小于15个字符 例如:发信人昵称设置为"小红"，发信地址为"test@example.com"，收信人看到的发信地址为"小红"test@example.com
> https://help.aliyun.com/document_detail/29444.html

我便尝试看了下您的代码，并加入 FromAlias参数，但却报『Specified signature is not matched with our calculation.』，研究了许久未找到解决办法，能否帮忙看下怎样加入 FromAlias参数？

**Comment by thonatos** [comment]
我抽时间看下什么问题。
